[package]
name = "signum-node-rs"
version = "0.1.0"
authors = ["damccull <401104+damccull@users.noreply.github.com>"]
edition = "2021"
rust-version = "1.84.0"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "signum-node-rs"

[features]
default = ["web"]
bunyan = ["dep:tracing-bunyan-formatter"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]
web = ["dioxus/web"]

[dependencies]
actix-web = { version = "4.5.1", features = ["rustls"] }
anyhow = "1.0"
config = "0.14.0"
console-subscriber = { version = "0.2.0", optional = true }
dioxus = { version = "0.6.0", features = ["fullstack", "router"] }
futures = "0.3.30"
itertools = "0.13.0"
num-bigint = { version = "0.4.6", features = ["serde"] }
reqwest = { version = "0.12.12", features = ["json", "rustls-tls", "charset", "http2", "macos-system-configuration"], default-features = false }
rustls-platform-verifier = { version = "0.5.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "3.9" }
surrealdb = { version = "2.1.4", features = ["kv-mem"] }
thiserror = "1.0.63"
tokio = { version = "1.39", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-actix-web = "0.7.11"
tracing-bunyan-formatter = { version = "0.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
url = { version = "2.5", features = ["serde"] }
uuid = { version = "1.10.0", features = ["v4"] }
wasm-bindgen = "=0.2.97"

[dev-dependencies]
once_cell = "1.19.0"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
