database:
  filename: "ws://localhost:8002"
node:
  cash_back_id: "15595382771538009899"
  network: "Signum"
b1protocol:
  # Settings that apply to general Peer to Peer work
  base_url: http://localhost:8123
  listen_address: "0.0.0.0"
  listen_port: 8123
  my_address: "rustdevnode.signumoasis.xyz:80"
  snr_reward_address: S-C9TD-24WW-RUD3-FGHVJ
  # bootstrap_peers:
  #   - "p2p.signumoasis.xyz:80"
  #   - "us-east.signum.network"
